CXX         = g++
#CXXFLAGS   = -O2 -Wall -Wno-switch -Wreorder -Wunused-function -ggdb -std=c++11 -DNDEBUG -DREENTRANT
CXXFLAGS    = -O2 -Wall -Wno-switch -Wno-reorder -Wno-unused-function -ggdb -std=c++11 -D_DEBUG -DREENTRANT
INCLUDES    = -I/usr/include -I/usr/local/include 
LFLAGS      = -L./ -L/usr/lib -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu
LIBS        = -lstdc++ -lpthread
